### ISSUE TITLE
游戏中提取的Live2d无法加载

### ISSUE THREAD

**Issue by picpo** [EYHN/hexo-helper-live2d#136]
**描述你的问题**
我在游戏中提取了人物的live2d资源，能用Cubism3Viewer打开  
![](https://ww1.sinaimg.cn/large/007i4MEmgy1fztmggwd8qj31420pwqb4.jpg)
但是在hexo中使用时发现如下问题，以致无法让live2d出现在网页中
![](https://ww1.sinaimg.cn/large/007i4MEmgy1fztmhxddwlj31190ky0uv.jpg)  
ERROR Plugin load failed: hexo-helper-live2d
Error: ENOTDIR: not a directory, scandir 'F:\blog\live2d_models\aierdeliqi_4.model.json'
    at Object.fs.readdirSync (fs.js:904:18)
    at listFiles (F:\blog\node_modules\hexo-helper-live2d\lib\listFiles.js:17:20)
    at loadModelFrom (F:\blog\node_modules\hexo-helper-live2d\lib\loadModelFrom.js:26:22)
    at F:\blog\node_modules\hexo-helper-live2d\index.js:117:11
    at fs.readFile.then.script (F:\blog\node_modules\hexo\lib\hexo\index.js:232:12)
    at tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\blog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (F:\blog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (F:\blog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (F:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\blog\node_modules\bluebird\js\release\promise.js:638:18)
    at F:\blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at F:\blog\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

另外，本人对live2d等不是非常精通，烦请大佬帮我查看问题
**复现步骤**
复现此问题的步骤

出现问题的网站地址:
**将 `log` 选项设置为 `true` 来显示完整的日志.**
`_config.yml` 中的配置:

```yaml

live2d:

```

控制台输出:

1. 打开'...'
2. 双击'...'
3. 滑动到'...'
4. 发现'...'错误

**预期的行为**
请简明清晰地描述此操作预期的结果

**屏幕截图**
如果可能, 请添加一些屏幕截图来更好地描述你的问题

**环境信息(请务必填写下列信息)**
- 设备: [e.g. iPhone 6, PC]
- 操作系统: [e.g. iOS 8.1, Windows 10]
- 浏览器 [e.g. Chrome 66, Safari 11.2]
- hexo-helper-live2d: [e.g. 3.0.0]
> 使用 `npm ls hexo-helper-live2d` 来获取当前插件版本.

**额外的信息**
请在此处描述其他的内容

- [ ] 我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [ ] 我已仔细阅读[README](../README.md)中的相关内容。

> 将 `[ ]` 变为 `[x]` 来表示我接受了这些问题。

@EYHN @xiazeyu

**Comment by Darkspirit2017** [comment]
目前为止好像还没有推出支持moc3的版本吧, 我也以前也尝试过AzurLane的live2d, 但没有一个是成功的

**Comment by xiazeyu** [comment]
moc3的官方repo: https://github.com/Live2D/CubismJsComponents

还是希望您能确认一下相关的路径没有问题
因为从控制台报错来看，他把.model.json当成一个目录了

**Comment by picpo** [comment]
> 
> 
> moc3的官方repo: https://github.com/Live2D/CubismJsComponents
> 
> 还是希望您能确认一下相关的路径没有问题
> 因为从控制台报错来看，他把.model.json当成一个目录了

路径换成文件夹了
似乎也不太行。。。
![](http://wx1.sinaimg.cn/mw690/006QkgcIly1g00fup3brij3074089glh.jpg)
![](http://wx3.sinaimg.cn/mw690/006QkgcIly1g00fur57wbj31190ky74q.jpg)
![](http://wx3.sinaimg.cn/mw690/006QkgcIly1g00fuom4wzj30hu07mglp.jpg)
![](http://wx3.sinaimg.cn/mw690/006QkgcIly1g00fumhpoxj31bq0ranoe.jpg)

**Comment by honjun** [comment]
3.0要3.0的webSDK才能显示

**Comment by purofle** [comment]
我也有同样的问题
