### ISSUE TITLE
when I use hexo clean, it shows error, please help!

### ISSUE THREAD

**Issue by Davidietop** [EYHN/hexo-helper-live2d#170]
`M:\github_perosonalweb\blog>hexo clean                                                                                  INFO  Validating config                                                                                                 FATAL YAMLException: duplicated mapping key at line 851, column -278:                                                       live2d:                                                                                                                 ^                                                                                                                       at generateError (M:\github_perosonalweb\blog\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)                        at throwError (M:\github_perosonalweb\blog\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)                            at storeMappingPair (M:\github_perosonalweb\blog\node_modules\js-yaml\lib\js-yaml\loader.js:335:7)                      at readBlockMapping (M:\github_perosonalweb\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1098:9)                     at composeNode (M:\github_perosonalweb\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)                         at readDocument (M:\github_perosonalweb\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1525:3)                         at loadDocuments (M:\github_perosonalweb\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1588:5)                        at Object.load (M:\github_perosonalweb\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1614:19)                         at Hexo.yamlHelper (M:\github_perosonalweb\blog\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)                    at Hexo.tryCatcher (M:\github_perosonalweb\blog\node_modules\bluebird\js\release\util.js:16:23)                         at Hexo.<anonymous> (M:\github_perosonalweb\blog\node_modules\bluebird\js\release\method.js:15:34)                      at M:\github_perosonalweb\blog\node_modules\hexo\lib\hexo\render.js:75:22                                               at tryCatcher (M:\github_perosonalweb\blog\node_modules\bluebird\js\release\util.js:16:23)                              at Promise._settlePromiseFromHandler (M:\github_perosonalweb\blog\node_modules\bluebird\js\release\promise.js:547:31)                                                                                                                           at Promise._settlePromise (M:\github_perosonalweb\blog\node_modules\bluebird\js\release\promise.js:604:18)              at Promise._settlePromise0 (M:\github_perosonalweb\blog\node_modules\bluebird\js\release\promise.js:649:10)             at Promise._settlePromises (M:\github_perosonalweb\blog\node_modules\bluebird\js\release\promise.js:729:18)             at _drainQueueStep (M:\github_perosonalweb\blog\node_modules\bluebird\js\release\async.js:93:12)                        at _drainQueue (M:\github_perosonalweb\blog\node_modules\bluebird\js\release\async.js:86:9)                             at Async._drainQueues (M:\github_perosonalweb\blog\node_modules\bluebird\js\release\async.js:102:5)                     at Immediate.Async.drainQueues [as _onImmediate] (M:\github_perosonalweb\blog\node_modules\bluebird\js\release\async.js:15:14)                                                                                                                  at processImmediate (internal/timers.js:461:21) {                                                                     reason: 'duplicated mapping key',                                                                                       mark: Mark {                                                 `

config in `_config.yml`:

```yaml

live2d:

```
![image](https://user-images.githubusercontent.com/44538872/100403613-50957100-309a-11eb-9efa-f4101133b47d.png)
But live2d can work after `hexo g && hexo d`, however, this error is annoying.

**Comment by Davidietop** [comment]
I solved it by merging "live2d:"'s content.
